Create the friendship model and its functions
jacobo12montes/ror-social-scaffold pull request #2
Opened 2021-02-26 20:19 UTC by jacobo12montes

- Generate the friendship model(throught table)
- Create the relations on the models
- Create the controller for friendship
- Add the namespace in the config/routes.rb file
- Run and verify the migrations

2021-02-27 09:29 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @jacobo12montes  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Remove the small empty button which is next to the name of the current user from the users list
- [x] The confirm and rehect buttons are combined in one button, fix that issue as well
- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from Pathwright)
- [ ] Add unit and integration tests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from the pathwright)
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-03-07 22:31 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @jacobo12montes, you have done well on this project, adding tests and implementing the previous TSE requirements.

Let's make a few changes, and we will be done.

- [x] Clicking on the see profile link produces an error. 
<img width="935" alt="Screen Shot 2021-03-07 at 10 07 11 PM" src="https://user-images.githubusercontent.com/5264771/110255678-391d2c80-7f95-11eb-8c72-fa5075e2c062.png">

- [ ] Add unit test for all models, don't forget to add integration test as well

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-07 22:31 UTC, acushlakoncept commented on app/views/posts/index.html.erb
> +  <% end %>
There should be absolutely NO logic in views

2021-03-07 22:31 UTC, acushlakoncept commented on app/views/shared/_flash_messages.html.erb
> +<% end %>
There should be absolutely NO logic in views

2021-03-07 22:31 UTC, acushlakoncept commented on app/views/shared/_friendship_status.html.erb
> +<% end %>
There should be absolutely NO logic in views

2021-03-07 22:31 UTC, acushlakoncept commented on app/views/shared/_session_links.html.erb
> +<% end %>
There should be absolutely NO logic in views

2021-03-07 22:31 UTC, acushlakoncept commented on app/views/shared/_user_posts.html.erb
> +<% end %>
There should be absolutely NO logic in views

2021-03-14 05:53 UTC, oloomoses requested changes
## Changes Required :recycle: 
Hello team, you have done a great job implementing the changes from the previous review. 
There are some critical issues that must be addressed before this project can be approved

### Required
- [x] Kindly Ensure that the linter and rubocop configuration is correct and all checks are passing on Github.
- [ ] Some of your tests are failing, Kindly fix them.

### Optional
- [ ] the add, confirms, and reject are working perfectly. It would be better to turn them into buttons for user-friendliness.

Kindly address the above issues before submitting another review.
Feel free to leave a message on slack in case of doubts or concerns.

_slack: Oloo Moses_

2021-03-23 16:18 UTC, jacobo12montes commented
Add the missing test and fix the failing test

2021-03-23 16:32 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @jacobo12montes**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] Please make sure to setup your linters probably, check if they pass, and request another code review.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-03-23 20:19 UTC, MahmoudBakr23 requested changes
# **Changes Required ⚠️**

<hr>

Hello there 👋
This is a great effort you're doing in this project so far. However, I'm afraid that the linter isn't well-configured yet. you should see the checks passing in the PR down below. Currently, I cannot see that, so kindly implement this issue to get the milestone approved 😊
good luck and happy coding 👍

2021-03-23 22:43 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:
**Hi Juan!
Great job so far:clap::clap:. The app is working as expected. However, we need to fix the failing linter errors to get this project approved:muscle:.**
**To improve**

- [ ] As highlighted by the last reviewer. Make sure the linter checks are all passing before submitting the PR for re-review. Kindly fix the linter errors.

 [Optional ]

- Kindly move the logic in application.html.erb under layout in view to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) on how to use a helper in rails. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright.

Make the above required changes and when you are ready, request another review.
Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

2021-03-26 10:08 UTC, oloomoses approved these changes
# Congratulations, Milestone Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this milestone :muscle: 
Feel free to merge and close this pull request.**


**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-03-29 16:29 UTC, merged